Object=SingleList.c
SingList:$(Object)
	@echo "Building..."
	gcc -o SingleList $(Object)
	@echo "$(Object) was builded."
.PHONY:run
run:
	./SingleList
.PHONY:clean
clean:
	rm -rf *.o SingleList
	@echo "Clean finished"
